import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0E1327',
        width: '100%',
    },
    header: {marginLeft: 30, flexDirection: 'row', marginTop: 50},
    headerText: {color: '#fff', marginLeft: 20, fontWeight: '800', fontSize: 16},
    headerImage: {marginTop: 3},
    headerView:{flexDirection: 'row', marginLeft: 20, marginTop: 30},
    headerViewText: {marginLeft: 20},
    solText: {color: '#FFFFFF', fontWeight: '600'},
    solTxt: {color: '#FFFFFF', color: '#B9C1D9'},
    balanceView: {marginLeft: 140},
    balTxt: {color: '#FFFFFF', color: '#B9C1D9', fontSize: 10},
    valTxt: {color: '#FFFFFF', fontSize: 18, fontWeight: '600'},
    addressInput: {
        width: '78%',
        height: 50,
        borderWidth: 1,
        borderColor: '#252A4D',
        alignSelf: 'center',
        marginTop: 16,
        marginLeft: 20,
        color: '#FFFFFF',
    },
    amountInput: {
    width: '88%',
    height: 50,
    borderWidth: 1,
    borderColor: '#252A4D',
    alignSelf: 'center',
    marginTop: 16,
    marginLeft: 20,},
    container: {
        flex: 1,
        backgroundColor: '#0E1327',
        width: '100%',
    },
    header: {marginLeft: 30, flexDirection: 'row', marginTop: 50},
    headerText: {color: '#fff', marginLeft: 20, fontWeight: '800', fontSize: 16},
    headerImage: {marginTop: 3},
    headerView:{flexDirection: 'row', marginLeft: 20, marginTop: 30},
    headerViewText: {marginLeft: 20},
    solText: {color: '#FFFFFF', fontWeight: '600'},
    solTxt: {color: '#FFFFFF', color: '#B9C1D9'},
    balanceView: {marginLeft: 140},
    balTxt: {color: '#FFFFFF', color: '#B9C1D9', fontSize: 10},
    valTxt: {color: '#FFFFFF', fontSize: 18, fontWeight: '600'},
    addressInput: {
        width: '78%',
        height: 50,
        borderWidth: 1,
        borderColor: '#252A4D',
        alignSelf: 'center',
        marginTop: 16,
        marginLeft: 20,
    },
    amountInput: {
    width: '88%',
    height: 50,
    borderWidth: 1,
    borderColor: '#252A4D',
    alignSelf: 'center',
    marginTop: 16,
    marginLeft: 20,
    },
    cardView:{width: '90%', height: '60%',backgroundColor: '#161A33', marginTop: 20, alignSelf: 'center', borderRadius: 10},
    enterAddTxt: {color: '#B9C1D9', marginLeft: 22, marginTop: 20},
    firstInputView:{flexDirection: 'row'},
    scannerImg:{marginTop: 30, marginLeft: 18},
    amountTxt:{color: '#B9C1D9', marginLeft: 22, marginTop: 20},
    maxTxt:{color: '#B9C1D9', marginTop: 20, marginLeft: 234},
    underLine:{width: '8%', borderWidth:0.2, borderColor:'#B9C1D9', marginLeft: 312},
    noteTxt:{color: '#B9C1D9', marginLeft: 22, marginTop: 20},
    noteText:{color: '#B9C1D9', marginLeft: 22, marginTop: 20},
    transactionTxt:{color: '#B9C1D9', marginLeft: 22, marginTop: 40},
    minValueTxt:{color: '#B9C1D9', marginLeft: 22, marginTop: 10},
    bottomButtonView:{width: '90%', height: '6%',backgroundColor: '#292C57', marginTop: '20%', alignSelf: 'center', borderRadius: 10},
    sendText:{alignSelf: 'center', color: '#F8F9FA', fontSize: 12, marginTop: 15},
    codeTxt:{color: '#FFFFFF', marginTop: 12, alignSelf: 'center'},
    solValueTxt:{color: '#FFFFFF', marginTop: 12, marginLeft: 5},
    noteText:{color: '#FFFFFF', marginTop: 12, marginLeft: 5},
    
})