import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0E1327',
        width: '100%',
    },
    tinyLogo: {
        marginLeft: 20
    },
    dollarLogo: {
        marginRight: 20
    },
    header: {flexDirection: 'row', marginTop: 60, justifyContent: 'space-between'},
    headerText: {color: '#FFFFFF', fontSize: 20},
    line: {
        width: "100%",
        borderWidth: 0.5,
        borderColor: "#161A33",
        marginTop: 25,
      },
    convertView: { flexDirection: "row"},
    convertText: {
        color: "#FFFFFF",
        marginLeft: 20,
        marginTop: 20,
        fontSize: 16,
        fontWeight: "700",
      },
    imageView:{ flexDirection: "row", marginTop: 22, marginLeft: 180 },
    settingImage: { marginLeft: 24 },
    cardView: {
        width: "90%",
        height: "50%",
        backgroundColor: "#161A33",
        marginTop: 20,
        alignSelf: "center",
        borderRadius: 10,
      },
    fromView: { flexDirection: "row", marginTop: 20, marginLeft: 30 },
    fromText: { color: "#B9C1D9" },
    fromInnerView: { flexDirection: "row", marginLeft: 210 },
    btcText: { color: "#B9C1D9" },
    dropDownImage: { marginTop: 4, marginLeft: 6 },
    inputField: {
        flexDirection: "row",
        marginTop: 20,
        marginLeft: 30,
        borderWidth: 1,
        borderColor: "#B9C1D9",
        width: "82%",
        height: "14%",
        borderRadius: 2,
      },
    btcTextValue: {
        color: "#FFFFFF",
        marginTop: 16,
        marginLeft: 20,
        fontWeight: "500",
        fontSize: 16,
      },
      btcView: { flexDirection: "row", marginLeft: 150, marginTop: 16 },
      btcImg: { marginTop: 4 },
      btcTxt: {
        color: "#FFFFFF",
        marginLeft: 16,
        fontWeight: "500",
        fontSize: 16,
      },
      convertImg: {marginTop: 50, marginLeft: 160},
      toView: { flexDirection: "row", marginTop: 20, marginLeft: 30 },
      toTxt: { color: "#B9C1D9" },
      usdView: { flexDirection: "row", marginLeft: 226 },
      usdtTxt: { color: "#B9C1D9" },
      drpDwnImage: { marginTop: 4, marginLeft: 6 },
      inputUsdView: {
        flexDirection: "row",
        marginTop: 20,
        marginLeft: 30,
        borderWidth: 1,
        borderColor: "#B9C1D9",
        width: "82%",
        height: "14%",
        borderRadius: 2,
      },
      usdtTextValue: {
        color: "#FFFFFF",
        marginTop: 16,
        marginLeft: 20,
        fontWeight: "500",
        fontSize: 16,
      },
      innerUsdtView: { flexDirection: "row", marginLeft: 110, marginTop: 16 },
      usdImg: { marginTop: 4 },
      usdText:{
        color: "#FFFFFF",
        marginLeft: 16,
        fontWeight: "500",
        fontSize: 16,
      },
    cardBottomView: {flexDirection: 'row'},
    bottomTxt: {color: '#B9C1D9', marginLeft: 30, marginTop: 40},
    btmPerTxt: {color: '#B9C1D9', marginLeft: 150, marginTop: 40},
    preViewButton: {width: '90%', height: '6%',backgroundColor: '#613AF1', marginTop: '40%', alignSelf: 'center', borderRadius: 10},
    preTxt: {alignSelf: 'center', color: '#F8F9FA', fontSize: 12, marginTop: 15},
});